In [7]:
import pandas as pd

data = pd.read_csv("./data/ETS_Database_v31.csv", sep="\t")

In [10]:
# remove weird date
agg_dates = ['Total 3rd trading period (13-20)', 
             'Total 2nd trading period (08-12)',
             'Total 1st trading period (05-07)']
d1 = data[~data['year'].isin(agg_dates)]

In [11]:
d1

,country,country_code,ETS information,main activity sector name,unit,value,year
0,Finland,FI,1.1 Freely allocated allowances,33 Manufacture of mineral wool,tonne of CO2 equ.,85278.0,2013
1,Finland,FI,1.1 Freely allocated allowances,33 Manufacture of mineral wool,tonne of CO2 equ.,53229.0,2017
2,Finland,FI,1.1.1 Free allocation to existing entities (Ar...,33 Manufacture of mineral wool,tonne of CO2 equ.,21480.0,2006
3,Finland,FI,1.1.1 Free allocation to existing entities (Ar...,33 Manufacture of mineral wool,tonne of CO2 equ.,83795.0,2014
4,Finland,FI,1.1.1 Free allocation to existing entities (Ar...,33 Manufacture of mineral wool,tonne of CO2 equ.,64072.0,2015
5,Finland,FI,1.1.3 Free allocation for modernisation of ele...,33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2016
6,Finland,FI,2. Verified emissions,33 Manufacture of mineral wool,tonne of CO2 equ.,24267.0,2005
7,Finland,FI,4.2 Surrendered certified emission reductions ...,33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2007
8,Finland,FI,4.2 Surrendered certified emission reductions ...,33 Manufacture of mineral wool,tonne of CO2 equ.,588.0,2008
9,Finland,FI,4.2 Surrendered certified emission reductions ...,33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2010
10,Finland,FI,4.3 Surrendered emission reduction units (ERUs),33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2007
11,Finland,FI,4.3 Surrendered emission reduction units (ERUs),33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2008
12,Finland,FI,1.1 Freely allocated allowances,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,12973.0,2016
13,Finland,FI,4.1 Surrendered EU allowances (EUAs and EUAAs),34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2005
14,Finland,FI,4.2 Surrendered certified emission reductions ...,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2006
15,Finland,FI,4.3 Surrendered emission reduction units (ERUs),34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2006
16,Finland,FI,1.1 Freely allocated allowances,35 Production of pulp,tonne of CO2 equ.,709832.0,2007
17,Finland,FI,1.1 Freely allocated allowances,35 Production of pulp,tonne of CO2 equ.,521204.0,2016
18,Finland,FI,2. Verified emissions,35 Production of pulp,tonne of CO2 equ.,532737.0,2006
19,Finland,FI,2. Verified emissions,35 Production of pulp,tonne of CO2 equ.,417794.0,2011
20,Finland,FI,4. Total surrendered units,35 Production of pulp,tonne of CO2 equ.,311554.0,2009
21,Finland,FI,4. Total surrendered units,35 Production of pulp,tonne of CO2 equ.,417794.0,2011
22,Finland,FI,4. Total surrendered units,35 Production of pulp,tonne of CO2 equ.,389656.0,2012
23,Finland,FI,4.1 Surrendered EU allowances (EUAs and EUAAs),35 Production of pulp,tonne of CO2 equ.,481072.0,2005
24,Finland,FI,4.2 Surrendered certified emission reductions ...,35 Production of pulp,tonne of CO2 equ.,0.0,2006
25,Finland,FI,4.3 Surrendered emission reduction units (ERUs),35 Production of pulp,tonne of CO2 equ.,0.0,2005
26,Finland,FI,1.1.1 Free allocation to existing entities (Ar...,38 Production of nitric acid,tonne of CO2 equ.,268247.0,2014
27,Finland,FI,2. Verified emissions,38 Production of nitric acid,tonne of CO2 equ.,1691.0,2007
28,Finland,FI,2. Verified emissions,38 Production of nitric acid,tonne of CO2 equ.,1016.0,2008
29,Finland,FI,2. Verified emissions,38 Production of nitric acid,tonne of CO2 equ.,193699.0,2016
...,...,...,...,...,...,...,...
51074,Netherlands,NL,4.3 Surrendered emission reduction units (ERUs),29 Production of cement clinker,tonne of CO2 equ.,0.0,2006
51075,Netherlands,NL,4.3 Surrendered emission reduction units (ERUs),29 Production of cement clinker,tonne of CO2 equ.,0.0,2009
51076,Netherlands,NL,4.3 Surrendered emission reduction units (ERUs),29 Production of cement clinker,tonne of CO2 equ.,0.0,2011
51077,Portugal,PT,4. Total surrendered units,31 Manufacture of glass,tonne of CO2 equ.,596629.0,2012
51078,Portugal,PT,4.3 Surrendered emission reduction units (ERUs),31 Manufacture of glass,tonne of CO2 equ.,0.0,2006
51079,Portugal,PT,1.1 Freely allocated allowances,32 Manufacture of ceramics,tonne of CO2 equ.,429573.0,2011
51080,Portugal,PT,2. Verified emissions,32 Manufacture of ceramics,tonne of CO2 equ.,169682.0,2011
51081,Portugal,PT,2. Verified emissions,32 Manufacture of ceramics,tonne of CO2 equ.,130100.0,2012
51082,Portugal,PT,4. Total surrendered units,32 Manufacture of ceramics,tonne of CO2 equ.,793136.0,2005
51083,Portugal,PT,4. Total surrendered units,32 Manufacture of ceramics,tonne of CO2 equ.,545017.0,2013
51084,Portugal,PT,4. Total surrendered units,32 Manufacture of ceramics,tonne of CO2 equ.,488485.0,2014
51085,Portugal,PT,4. Total surrendered units,32 Manufacture of ceramics,tonne of CO2 equ.,491980.0,2015
51086,Portugal,PT,4.2 Surrendered certified emission reductions ...,32 Manufacture of ceramics,tonne of CO2 equ.,0.0,2007
51087,Portugal,PT,4.2 Surrendered certified emission reductions ...,32 Manufacture of ceramics,tonne of CO2 equ.,0.0,2008
51088,Portugal,PT,4.2 Surrendered certified emission reductions ...,32 Manufacture of ceramics,tonne of CO2 equ.,16962.0,2010
51089,Portugal,PT,4.3 Surrendered emission reduction units (ERUs),32 Manufacture of ceramics,tonne of CO2 equ.,0.0,2011
51090,Portugal,PT,2. Verified emissions,33 Manufacture of mineral wool,tonne of CO2 equ.,80890.0,2007
51091,Portugal,PT,4.1 Surrendered EU allowances (EUAs and EUAAs),33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2008
51092,Portugal,PT,4.1 Surrendered EU allowances (EUAs and EUAAs),33 Manufacture of mineral wool,tonne of CO2 equ.,0.0,2010
51093,Portugal,PT,1.1 Freely allocated allowances,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,9763.0,2013
51094,Portugal,PT,1.1 Freely allocated allowances,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,11991.0,2014
51095,Portugal,PT,1.1.1 Free allocation to existing entities (Ar...,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,11340.0,2017
51096,Portugal,PT,1.1.2 Free allocation from the new entrants re...,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2016
51097,Portugal,PT,1.1.3 Free allocation for modernisation of ele...,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2016
51098,Portugal,PT,2. Verified emissions,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,14504.0,2015
51099,Portugal,PT,4.1 Surrendered EU allowances (EUAs and EUAAs),34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2006
51100,Portugal,PT,4.1 Surrendered EU allowances (EUAs and EUAAs),34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2009
51101,Portugal,PT,4.3 Surrendered emission reduction units (ERUs),34 Production or processing of gypsum or plast...,tonne of CO2 equ.,0.0,2005
51102,Portugal,PT,1.1 Freely allocated allowances,35 Production of pulp,tonne of CO2 equ.,179843.0,2005
51103,Portugal,PT,1.1 Freely allocated allowances,35 Production of pulp,tonne of CO2 equ.,136857.0,2013

In [16]:
d1['year'].value_counts()

2012    3446
2009    3331
2011    3330
2010    3329
2008    3328
2016    3172
2017    3171
2014    3162
2015    3158
2013    3144
2007    3122
2006    2916
2005    2905
Name: year, dtype: int64

In [20]:
d1.to_csv('./data/d1.csv', sep='\t')

In [21]:
d1['unit'].value_counts()

tonne of CO2 equ.    41514
Name: unit, dtype: int64

In [ ]:
pop = pd.read_csv('./data/eu_pop/world_pop.csv')

In [42]:
p1 = pop[['Country Name', '2017']]
p1_list = p1['Country Name'].unique()

In [65]:
eu_list = d1['country'].unique()[:-1] # remove the strange NER 300 thing

In [69]:
eu_list.astype(str)

array(['Finland', 'Portugal', 'Romania', 'Poland', 'Latvia', 'France',
       'Spain', 'Slovenia', 'Sweden', 'United Kingdom', 'Slovakia',
       'Italy', 'Liechtenstein', 'Greece', 'Netherlands', 'Denmark',
       'Estonia', 'Austria', 'Hungary', 'Cyprus', 'Czech Republic',
       'Croatia', 'Luxembourg', 'Germany', 'Belgium', 'Bulgaria',
       'Iceland', 'Ireland', 'Lithuania', 'Malta', 'Norway'], dtype='<U14')

In [75]:
target_countries = list(set(eu_list) & set(p1_list) ) # removed slovakia lol

In [82]:
df_2018 = d1[data['country'].isin(target_countries)]
df_2018 = df_2018[df_2018['year'] == '2017']
df_2018

/home/louiselai88gmail/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,country,country_code,ETS information,main activity sector name,unit,value,year
1,Finland,FI,1.1 Freely allocated allowances,33 Manufacture of mineral wool,tonne of CO2 equ.,53229.0,2017
60,Finland,FI,1.1 Freely allocated allowances,42 Production of bulk chemicals,tonne of CO2 equ.,550316.0,2017
67,Finland,FI,2. Verified emissions,42 Production of bulk chemicals,tonne of CO2 equ.,531690.0,2017
75,Finland,FI,1.1.1 Free allocation to existing entities (Ar...,43 Production of hydrogen and synthesis gas,tonne of CO2 equ.,148118.0,2017
94,Finland,FI,1.1.2 Free allocation from the new entrants re...,24 Production of pig iron or steel,tonne of CO2 equ.,120357.0,2017
96,Portugal,PT,1.1.1 Free allocation to existing entities (Ar...,43 Production of hydrogen and synthesis gas,tonne of CO2 equ.,34284.0,2017
97,Portugal,PT,1.1.2 Free allocation from the new entrants re...,43 Production of hydrogen and synthesis gas,tonne of CO2 equ.,0.0,2017
105,Portugal,PT,1.1 Freely allocated allowances,44 Production of soda ash and sodium bicarbonate,tonne of CO2 equ.,0.0,2017
113,Romania,RO,1.1.1 Free allocation to existing entities (Ar...,10 Aviation,tonne of CO2 equ.,314061.0,2017
153,Finland,FI,4. Total surrendered units,38 Production of nitric acid,tonne of CO2 equ.,187289.0,2017
159,Finland,FI,1.1.2 Free allocation from the new entrants re...,42 Production of bulk chemicals,tonne of CO2 equ.,0.0,2017
163,Finland,FI,4. Total surrendered units,42 Production of bulk chemicals,tonne of CO2 equ.,531690.0,2017
167,Finland,FI,1.1.3 Free allocation for modernisation of ele...,43 Production of hydrogen and synthesis gas,tonne of CO2 equ.,0.0,2017
182,Latvia,LV,1.1.2 Free allocation from the new entrants re...,32 Manufacture of ceramics,tonne of CO2 equ.,0.0,2017
184,Latvia,LV,1.1.3 Free allocation for modernisation of ele...,32 Manufacture of ceramics,tonne of CO2 equ.,0.0,2017
187,France,FR,2. Verified emissions,20 Combustion of fuels,tonne of CO2 equ.,53607506.0,2017
221,Spain,ES,2. Verified emissions,41 Production of ammonia,tonne of CO2 equ.,617423.0,2017
230,Finland,FI,1.1.3 Free allocation for modernisation of ele...,24 Production of pig iron or steel,tonne of CO2 equ.,0.0,2017
258,Finland,FI,2. Verified emissions,99 Other activity opted-in under Art. 24,tonne of CO2 equ.,35681.0,2017
264,France,FR,1.1 Freely allocated allowances,10 Aviation,tonne of CO2 equ.,2026888.0,2017
270,France,FR,2. Verified emissions,10 Aviation,tonne of CO2 equ.,4063267.0,2017
287,Finland,FI,1.1.2 Free allocation from the new entrants re...,25 Production or processing of ferrous metals,tonne of CO2 equ.,0.0,2017
288,Finland,FI,1.1.3 Free allocation for modernisation of ele...,25 Production or processing of ferrous metals,tonne of CO2 equ.,0.0,2017
294,Finland,FI,1.1.2 Free allocation from the new entrants re...,28 Production or processing of non-ferrous metals,tonne of CO2 equ.,0.0,2017
295,Finland,FI,1.1.3 Free allocation for modernisation of ele...,28 Production or processing of non-ferrous metals,tonne of CO2 equ.,0.0,2017
304,Poland,PL,4. Total surrendered units,25 Production or processing of ferrous metals,tonne of CO2 equ.,1035787.0,2017
346,Finland,FI,2. Verified emissions,25 Production or processing of ferrous metals,tonne of CO2 equ.,83101.0,2017
354,Finland,FI,2. Verified emissions,28 Production or processing of non-ferrous metals,tonne of CO2 equ.,81132.0,2017
363,Slovenia,SI,1.1.1 Free allocation to existing entities (Ar...,20 Combustion of fuels,tonne of CO2 equ.,448284.0,2017
391,Portugal,PT,1.1.2 Free allocation from the new entrants re...,36 Production of paper or cardboard,tonne of CO2 equ.,15599.0,2017
...,...,...,...,...,...,...,...
50691,Poland,PL,1.1.3 Free allocation for modernisation of ele...,41 Production of ammonia,tonne of CO2 equ.,0.0,2017
50720,Portugal,PT,4. Total surrendered units,10 Aviation,tonne of CO2 equ.,1346983.0,2017
50728,Portugal,PT,1.1.3 Free allocation for modernisation of ele...,20 Combustion of fuels,tonne of CO2 equ.,0.0,2017
50757,Poland,PL,1.1 Freely allocated allowances,24 Production of pig iron or steel,tonne of CO2 equ.,6279718.0,2017
50766,Poland,PL,1.1 Freely allocated allowances,25 Production or processing of ferrous metals,tonne of CO2 equ.,1004397.0,2017
50776,Poland,PL,1.1 Freely allocated allowances,28 Production or processing of non-ferrous metals,tonne of CO2 equ.,1617976.0,2017
50794,Lithuania,LT,4. Total surrendered units,"30 Production of lime, or calcination of dolom...",tonne of CO2 equ.,25236.0,2017
50799,Lithuania,LT,1.1 Freely allocated allowances,31 Manufacture of glass,tonne of CO2 equ.,18729.0,2017
50827,Norway,NO,2. Verified emissions,32 Manufacture of ceramics,tonne of CO2 equ.,36566.0,2017
50849,Poland,PL,4. Total surrendered units,36 Production of paper or cardboard,tonne of CO2 equ.,1956247.0,2017
50853,Netherlands,NL,2. Verified emissions,20 Combustion of fuels,tonne of CO2 equ.,61290902.0,2017
50861,Netherlands,NL,1.1.3 Free allocation for modernisation of ele...,20-99 All stationary installations,tonne of CO2 equ.,0.0,2017
50876,Poland,PL,4. Total surrendered units,37 Production of carbon black,tonne of CO2 equ.,92410.0,2017
50882,Poland,PL,1.1.1 Free allocation to existing entities (Ar...,38 Production of nitric acid,tonne of CO2 equ.,663315.0,2017
50889,Poland,PL,1.1 Freely allocated allowances,41 Production of ammonia,tonne of CO2 equ.,1282698.0,2017
50896,Poland,PL,2. Verified emissions,41 Production of ammonia,tonne of CO2 equ.,1824964.0,2017
50911,Poland,PL,1.1.2 Free allocation from the new entrants re...,44 Production of soda ash and sodium bicarbonate,tonne of CO2 equ.,0.0,2017
50913,Poland,PL,1.1.3 Free allocation for modernisation of ele...,44 Production of soda ash and sodium bicarbonate,tonne of CO2 equ.,0.0,2017
50914,Poland,PL,2. Verified emissions,44 Production of soda ash and sodium bicarbonate,tonne of CO2 equ.,461402.0,2017
50930,Portugal,PT,4. Total surrendered units,20 Combustion of fuels,tonne of CO2 equ.,19715908.0,2017
50944,Portugal,PT,1.1.1 Free allocation to existing entities (Ar...,21 Refining of mineral oil,tonne of CO2 equ.,1563886.0,2017
50956,Portugal,PT,1.1.2 Free allocation from the new entrants re...,21-99 All industrial installations (excl. comb...,tonne of CO2 equ.,484820.0,2017
50968,Portugal,PT,1.1 Freely allocated allowances,24 Production of pig iron or steel,tonne of CO2 equ.,189071.0,2017
50978,Netherlands,NL,1.1.1 Free allocation to existing entities (Ar...,21-99 All industrial installations (excl. comb...,tonne of CO2 equ.,31881971.0,2017
50996,Netherlands,NL,1.1.2 Free allocation from the new entrants re...,24 Production of pig iron or steel,tonne of CO2 equ.,0.0,2017
51001,Netherlands,NL,4. Total surrendered units,24 Production of pig iron or steel,tonne of CO2 equ.,6955479.0,2017
51013,Portugal,PT,2. Verified emissions,24 Production of pig iron or steel,tonne of CO2 equ.,135143.0,2017
51028,Portugal,PT,1.1.3 Free allocation for modernisation of ele...,"30 Production of lime, or calcination of dolom...",tonne of CO2 equ.,0.0,2017
51064,Netherlands,NL,4. Total surrendered units,28 Production or processing of non-ferrous metals,tonne of CO2 equ.,29803.0,2017
51095,Portugal,PT,1.1.1 Free allocation to existing entities (Ar...,34 Production or processing of gypsum or plast...,tonne of CO2 equ.,11340.0,2017

In [95]:
eu_emissions = df_2018.groupby(['country']).sum()

In [100]:
# p1 = population of all countries
# eu_emissions = just the emmisions of eu countries in 2018

# Left join
joined = eu_emissions.join(p1.set_index("Country Name"), on="country", how="left")
joined.columns=['emissions', 'population'] # rename cols

In [102]:
joined.head()

            emissions  population
country
Austria   332863258.0   8809212.0
Belgium   513933110.0  11372068.0
Bulgaria  281218138.0   7075991.0
Croatia    84717893.0   4125700.0
Cyprus     37941570.0   1179551.0

In [102]:
joined.head()

            emissions  population
country
Austria   332863258.0   8809212.0
Belgium   513933110.0  11372068.0
Bulgaria  281218138.0   7075991.0
Croatia    84717893.0   4125700.0
Cyprus     37941570.0   1179551.0

In [107]:
joined['emissions_per_capita'] = joined['emissions'] / joined['population']

In [111]:
joined

                   emissions  population  emissions_per_capita
country
Austria         3.328633e+08   8809212.0             37.785815
Belgium         5.139331e+08  11372068.0             45.192582
Bulgaria        2.812181e+08   7075991.0             39.742580
Croatia         8.471789e+07   4125700.0             20.534186
Cyprus          3.794157e+07   1179551.0             32.166112
Czech Republic  5.556687e+08  10591323.0             52.464520
Denmark         1.430522e+08   5769603.0             24.794119
Estonia         1.003566e+08   1315480.0             76.288983
Finland         2.783600e+08   5511303.0             50.507120
France          1.115216e+09  67118648.0             16.615589
Germany         3.419166e+09  82695000.0             41.346703
Greece          3.936594e+08  10760421.0             36.584013
Hungary         1.953778e+08   9781127.0             19.974974
Iceland         2.312156e+07    341284.0             67.748749
Ireland         1.647949e+08   4813608.0             34.235218
Italy           1.400911e+09  60551416.0             23.135884
Latvia          2.738288e+07   1940740.0             14.109506
Liechtenstein   7.777000e+03     37922.0              0.205079
Lithuania       8.499733e+07   2827721.0             30.058600
Luxembourg      2.010220e+07    599449.0             33.534457
Malta           5.962234e+06    465292.0             12.813962
Netherlands     7.878214e+08  17132854.0             45.983079
Norway          2.302677e+08   5282223.0             43.592945
Poland          1.449006e+09  37975841.0             38.155992
Portugal        2.545789e+08  10293718.0             24.731479
Romania         4.470586e+08  19586539.0             22.824786
Slovenia        5.013926e+07   2066748.0             24.259976
Spain           1.246461e+09  46572028.0             26.764153
Sweden          2.740350e+08  10067744.0             27.219106
United Kingdom  1.211548e+09  66022273.0             18.350591

In [112]:
joined.to_csv('./data/joined.csv', sep='\t')